In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.3401, 0.8042, 0.5353],
        [0.6047, 0.3208, 0.8642],
        [0.1493, 0.3751, 0.7160],
        [0.4175, 0.9959, 0.1544],
        [0.0742, 0.4730, 0.8002]])


In [2]:
def activation(x):         #sigmoid function
    return 1 / (1+ torch.exp(-x))

In [3]:
torch.manual_seed(7)
features = torch.randn((1,5))
print("features:",features)
weights = torch.randn_like(features)
print("weights:",weights)
bias = torch.randn((1,1))
print("bias:",bias)

features: tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
weights: tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
bias: tensor([[0.3177]])


In [4]:
'''h = torch.matmul(features,weights.t())
print("h:",h)
sum = torch.sum(h, bias)'''

y = activation(torch.sum(features * weights) + bias)
print("y:",y)

y: tensor([[0.1595]])


In [5]:
'''weights = weights.view(5,1)
mul = torch.mm(features, weights)
# mul = torch.matmul(features,weights)
print("mul:",mul)'''
y = activation(torch.mm(features, weights.view(5,1))+ bias)
y

tensor([[0.1595]])

In [6]:
torch.manual_seed(7)

features = torch.randn((1,3))
'''print("features:",features)
print(features.shape[1])
'''
n_input = features.shape[1]
#print("input:",n_input)
n_hidden = 2
n_output = 1
W1 = torch.randn(n_input, n_hidden)
#print('w1:',W1)
W2 = torch.randn(n_hidden, n_output)
#print('w2:',W2)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [7]:
y1 = activation(torch.mm(features, W1)+ B1)
y = activation(torch.mm(y1, W2)+ B2)
print(y)

tensor([[0.3171]])


In [8]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.05880071, 0.18318832, 0.09222065],
       [0.47882719, 0.80340218, 0.03579095],
       [0.18248002, 0.80172005, 0.53697275],
       [0.56561538, 0.39048819, 0.14571046]])

In [9]:
b = torch.from_numpy(a)
b

tensor([[0.0588, 0.1832, 0.0922],
        [0.4788, 0.8034, 0.0358],
        [0.1825, 0.8017, 0.5370],
        [0.5656, 0.3905, 0.1457]], dtype=torch.float64)

In [10]:
b.numpy()

array([[0.05880071, 0.18318832, 0.09222065],
       [0.47882719, 0.80340218, 0.03579095],
       [0.18248002, 0.80172005, 0.53697275],
       [0.56561538, 0.39048819, 0.14571046]])

In [11]:
b.mul_(2)

tensor([[0.1176, 0.3664, 0.1844],
        [0.9577, 1.6068, 0.0716],
        [0.3650, 1.6034, 1.0739],
        [1.1312, 0.7810, 0.2914]], dtype=torch.float64)

In [12]:
a

array([[0.11760143, 0.36637664, 0.18444131],
       [0.95765439, 1.60680437, 0.07158189],
       [0.36496005, 1.60344009, 1.07394549],
       [1.13123076, 0.78097639, 0.29142092]])